---
services:
  - name: mongodb@.service
    count: 3
  - name: mongodb-sidekick@.service
    count: 3
  - name: mongodb-configurator.service
  - name: cms-notifier@.service
    version: v21
    count: 2
  - name: cms-notifier-sidekick@.service
    count: 2
  - name: methode-content-importer@.service
    version: v23
    count: 2
  - name: methode-content-importer-sidekick@.service
    count: 2
  - name: binary-ingester@.service
    version: v35
    count: 2
  - name: binary-ingester-sidekick@.service
    count: 2
  - name: binary-writer@.service
    version: v37
    count: 2
  - name: binary-writer-sidekick@.service
    count: 2
  - name: methode-image-binary-transformer@.service
    version: v18
    count: 2
  - name: methode-image-binary-transformer-sidekick@.service
    count: 2
  - name: methode-image-model-transformer@.service
    version: v22
    count: 2
  - name: methode-image-model-transformer-sidekick@.service
    count: 2
  - name: nativerw@.service
    version: v25
    count: 2
  - name: nativerw-sidekick@.service
    count: 2
  - name: aggregate-healthcheck@.service
    version: v30
    count: 1
  - name: aggregate-healthcheck-sidekick@.service
    count: 1
  - name: synthetic-image-publication-monitor-ucs@.service
    version: v31
    count: 1
  - name: synthetic-image-publication-monitor-ucs-sidekick@.service
    count: 1
  - name: synthetic-image-publication-monitor-aws@.service
    version: v31
    count: 1
  - name: synthetic-image-publication-monitor-aws-sidekick@.service
    count: 1
  - name: kafka.service
  - name: kafka-sidekick.service
  - name: zookeeper.service
  - name: zookeeper-sidekick.service
  - name: splunk-forwarder.service
  - name: skydns.service
  - name: vulcan.service
  - name: methodeapi-endpoint.service
  - name: deployer.service
  - name: deployer.timer
  - name: diamond.service
  - name: elb-presence.service
  - name: image-cleaner.service
  - name: image-cleaner.timer

