services:
- name: diamond.service
- name: elb-dns-registrator.service
  version: v2.0.1
- name: elb-presence@.service
  count: 2
- name: kafka-rest-proxy-sidekick.service
- name: kafka-rest-proxy.service
  version: v1.0.0
- name: kafka.service
- name: mongodb-all.service
- name: mongodb-configurator.service
- name: mongodb-sidekick@.service
  count: 3
- name: mongodb@.service
  count: 3
- name: nativerw-sidekick@.service
  count: 2
- name: nativerw@.service
  version: v41
  count: 2
- name: zookeeper.service
- name: vulcan-config-builder.service
  version: v1.0.6
- name: vulcan.service
  version: v1.1.0