services:
- name: diamond.service
- name: fleet-unit-healthcheck-sidekick.service
- name: fleet-unit-healthcheck.service
  version: 1.0.1
- name: image-cleaner.service
  version: 1.0.0
- name: kafka-rest-proxy-sidekick.service
- name: kafka-rest-proxy.service
  version: v1.0.0
- name: kafka.service
- name: vulcan-config-builder.service
  version: v1.0.6
- name: vulcan.service
  version: v1.1.0
