---
services:
  - name: mongodb@.service
    count: 3
  - name: mongodb-sidekick@.service
    count: 3
  - name: mongodb-configurator.service
  - name: cms-notifier@.service
    version: v28
    count: 2
  - name: cms-notifier-sidekick@.service
    count: 2
  - name: methode-content-importer@.service
    version: v30
    count: 2
  - name: methode-content-importer-sidekick@.service
    count: 2
  - name: binary-ingester@.service
    version: v77
    count: 2
  - name: binary-ingester-sidekick@.service
    count: 2
  - name: binary-writer@.service
    version: v43
    count: 2
  - name: binary-writer-sidekick@.service
    count: 2
  - name: document-store-api@.service
    version: v20
    count: 1
  - name: document-store-api-sidekick@.service
    count: 1
  - name: methode-image-binary-transformer@.service
    version: v21
    count: 2
  - name: methode-image-binary-transformer-sidekick@.service
    count: 2
  - name: methode-image-model-transformer@.service
    version: v29
    count: 2
  - name: methode-image-model-transformer-sidekick@.service
    count: 2
  - name: nativerw@.service
    version: v35
    count: 2
  - name: nativerw-sidekick@.service
    count: 2
  - name: aggregate-healthcheck@.service
    count: 1
  - name: aggregate-healthcheck-sidekick@.service
    count: 1
  - name: synthetic-image-publication-monitor-ucs@.service
    version: v33
    count: 1
  - name: synthetic-image-publication-monitor-ucs-sidekick@.service
    count: 1
  - name: synthetic-image-publication-monitor-aws@.service
    version: v33
    count: 1
  - name: synthetic-image-publication-monitor-aws-sidekick@.service
    count: 1
  - name: coco-kafka-bridge@.service
    count: 2
  - name: coco-kafka-bridge-sidekick@.service
    count: 2
  - name: kafka-rest-proxy.service
  - name: kafka-rest-proxy-sidekick.service
  - name: mongodb-all.service          
  - name: system-healthcheck.service
  - name: system-healthcheck-sidekick.service
  - name: fleet-unit-healthcheck.service
  - name: fleet-unit-healthcheck-sidekick.service
  - name: kafka.service
  - name: zookeeper.service
  - name: splunk-forwarder.service
  - name: vulcan.service
  - name: methodeapi-endpoint.service
  - name: diamond.service
  - name: elb-presence.service
  - name: image-cleaner.service
  - name: image-cleaner.timer
  - name: mongodb-all.service
  - name: restorage-mongo@.service
    count: 1
  - name: restorage-mongo-sidekick@.service
    count: 1
  - name: mongo-backup.service
    desiredState: loaded
  - name: mongo-backup.timer
  - name: tunnel-registrator.service
  - name: elb-dns-registrator.service
  - name: publish-availability-monitor.service
  - name: vulcan-config-builder.service
