---
services:
  - name: mongodb@.service
    count: 3
  - name: mongodb-sidekick@.service
    count: 3
  - name: mongodb-configurator.service
  - name: cms-notifier@.service
    version: v15
    count: 2
  - name: cms-notifier-sidekick@.service
    count: 2
  - name: methode-content-importer@.service
    version: v21
    count: 2
  - name: methode-content-importer-sidekick@.service
    count: 2
  - name: binary-ingester@.service
    version: v27
    count: 2
  - name: binary-ingester-sidekick@.service
    count: 2
  - name: binary-writer@.service
    version: v30 
    count: 2
  - name: binary-writer-sidekick@.service
    count: 2
  - name: methode-image-binary-transformer@.service
    version: v15
    count: 2
  - name: methode-image-binary-transformer-sidekick@.service
    count: 2
  - name: methode-image-model-transformer@.service
    version: v19
    count: 2
  - name: methode-image-model-transformer-sidekick@.service
    count: 2
  - name: nativerw@.service
    version: v22 
    count: 2
  - name: nativerw-sidekick@.service
    count: 2
  - name: aggregate-healthcheck@.service
    count: 1
  - name: aggregate-healthcheck-sidekick@.service
    count: 1
  - name: synthetic-image-publication-monitor@.service
    count: 1
    version: v25
  - name: synthetic-image-publication-monitor-sidekick@.service
    count: 1
  - name: kafka.service
  - name: kafka-sidekick.service
  - name: zookeeper.service
  - name: zookeeper-sidekick.service
  - name: splunk-forwarder.service
  - name: skydns.service
  - name: vulcan.service
  - name: image-cleaner.service
  - name: image-cleaner.timer
  - name: methodeapi-endpoint.service
  - name: dashing-forwarder.service
  - name: deployer.service
  - name: deployer.timer
  - name: vulcan-elb-presence.service
  - name: diamond.service

