services:
- name: aggregate-healthcheck-sidekick@.service
  count: 1
- name: aggregate-healthcheck@.service
  version: v1.0.7
  count: 1
- name: elb-dns-registrator.service
  version: v2.0.1
- name: elb-presence@.service
  count: 2
- name: fleet-unit-healthcheck-sidekick.service
- name: fleet-unit-healthcheck.service
  version: 1.0.1
- name: os-upgrade.service
  desiredState: loaded
- name: system-healthcheck-sidekick.service
- name: system-healthcheck.service
  version: 1.0.1
- name: tunnel-registrator.service
- name: varnish-sidekick@.service
  count: 2
- name: varnish@.service
  version: v63
  count: 2
  sequentialDeployment: true
- name: vulcan-config-builder.service
  version: v1.1.0
- name: vulcan.service
  version: v1.1.0